### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/tools#11]
To allow us to continue using `curl` easily, let's go with

https://fastapi.tiangolo.com/advanced/security/http-basic-auth/

as a first step

**Comment by surchs** [comment]
Could also look at https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-with-a-github-app-on-behalf-of-a-user  for inspiration - GitHub Apps are also just services run on our own hardware that do things on GitHub ...
