### ISSUE TITLE
Deploy on new `fairmount` machine

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/tools#16]
- [x] pull `nightly` image for `openneuro_upload`
- [x] set up subdomain on Cloudflare (use upload.neurobagel.org for now)
- [x] Dockerized NGINX

**Comment by surchs** [comment]
Maybe upload.neurobagel.org/openneuro
?

**Comment by alyssadai** [comment]
@surchs, could you please also link the GH page with the Dockerized NGINX instructions?

**Comment by surchs** [comment]
Here are the basic docs on both: https://hackmd.io/@neurobagel/HJso7R0f0 will add more

**Comment by surchs** [comment]
thinking of deploying off `nightly` for now

**Comment by alyssadai** [comment]
For reviewer, see:

- https://upload.neurobagel.org/docs
- on the new `fairmount` machine, see `~/dataplace/tools/openneuro_upload` for .env file and README containing `docker run` command for container

**Comment by surchs** [comment]
Very nice 🎉 . All good, ready to close 🧑‍🍳
